### ISSUE TITLE
Values of ARF_RND_FLOOR,...

### ISSUE THREAD

**Issue by Chris00** [wjyoumans/arb-sys#1]
Thanks for your arb_sys package.  It would be nice to have the values of `ARF_RND_FLOOR`, `ARF_RND_CEIL`,... available as constants.

**Comment by wjyoumans** [comment]
Sure thing, I'll look into it.

**Comment by wjyoumans** [comment]
Constants were added in the last commit, they are located in `src/lib.rs`.

**Comment by Chris00** [comment]
Thanks.  However, the type of the constants is not right.  For example, `ARF_RND_FLOOR` is supposed to be used in, say, [`arf_sub`](https://docs.rs/arb-sys/0.2.5/arb_sys/arf/fn.arf_sub.html) and the `rnd` parameter is a `c_int` i.e., a `i32`.  (This is coherent with the C code where
```C
int arf_sub(arf_ptr z, arf_srcptr x, arf_srcptr y, slong prec, arf_rnd_t rnd);
#define arf_rnd_t fmpr_rnd_t
#define fmpr_rnd_t int
```

**Comment by wjyoumans** [comment]
Thanks, should be fixed now. I changed all constants from u32 to c_int. If any are inconsistent with the bindings let me know.
