### ISSUE TITLE
Name of the C lib

### ISSUE THREAD

**Issue by Chris00** [wjyoumans/arb-sys#3]
On Debian, the C library is named `flint-arb`.  It must be changed in `build.rs`.  Not sure how to perform autoconfiguration (I was thinking of using [cc](https://crates.io/crates/cc) to try to compile C files but maybe you have other ideas).  Unfortunately, it is not `pkg-config` enabled.

**Comment by wjyoumans** [comment]
Thanks for the info on Debian, I'll update the readme to warn people.

Ideally yes, we would have some autoconfiguration with the end goal being to compile arb so users can just add arb-sys to their dependencies. This isn't something I've started on yet, though I planned to use the gmp-mpfr-sys `build.rs` file as a reference: https://gitlab.com/tspiteri/gmp-mpfr-sys/-/blob/master/build.rs

**Comment by wjyoumans** [comment]
The readme is updated with your fix for Debian.
